-- Script SQL untuk membuat tabel di Supabase
-- Jalankan kode ini di fitur "SQL Editor" pada dashboard Supabase Anda.

-- Drop tabel lama agar tidak terjadi duplikasi saat script dijalankan ulang
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS menu CASCADE;
DROP TABLE IF EXISTS kantin CASCADE;

-- 1. Membuat tabel 'kantin'
CREATE TABLE kantin (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama TEXT NOT NULL,
  icon TEXT NOT NULL
);

-- 2. Membuat tabel 'menu'
CREATE TABLE menu (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kantin_id BIGINT REFERENCES kantin(id) ON DELETE CASCADE,
  nama TEXT NOT NULL,
  harga INT NOT NULL,
  img TEXT NOT NULL
);

-- 3. Membuat tabel 'orders'
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kantin_id BIGINT REFERENCES kantin(id) ON DELETE CASCADE,
  username TEXT NOT NULL,
  items TEXT NOT NULL,
  total_price INT NOT NULL,
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Membuat tabel 'reviews'
CREATE TABLE reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  review_text TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Memasukkan data awal (dummy data) untuk tabel kantin
INSERT INTO kantin (id, nama, icon) OVERRIDING SYSTEM VALUE VALUES 
  (1, 'USMAN 1', '🍱'),
  (2, 'USMAN 2', '🍲'),
  (3, 'USMAN 3', '🍜'),
  (4, 'USMAN 4', '🍹'),
  (5, 'USMAN 7', '☕'),
  (6, 'USMAN 8', '🍙');

-- Memasukkan data awal (dummy data) untuk tabel menu
INSERT INTO menu (kantin_id, nama, harga, img) VALUES 
  -- USMAN 1
  (1, 'Pentol', 5000, 'https://images.unsplash.com/photo-1596649281278-6bd3914a1c6a?w=400'),
  (1, 'Bakpao', 2500, 'https://images.unsplash.com/photo-1627916531398-ff2f1cf1d2ce?w=400'),
  (1, 'Gorengan', 1000, 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400'),
  -- USMAN 2
  (2, 'Pentol', 5000, 'https://images.unsplash.com/photo-1596649281278-6bd3914a1c6a?w=400'),
  (2, 'Bakpao', 2500, 'https://images.unsplash.com/photo-1627916531398-ff2f1cf1d2ce?w=400'),
  (2, 'Gorengan', 1000, 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400'),
  -- USMAN 3
  (3, 'Tempura', 1000, 'https://images.unsplash.com/photo-1581184953963-d159747d1286?w=400'),
  (3, 'Gorengan', 1000, 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400'),
  -- USMAN 4
  (4, 'Es Sachet', 3000, 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400'),
  (4, 'Le Minerale', 3000, 'https://images.unsplash.com/photo-1523362628745-0c100150b504?w=400'),
  (4, 'Nabati', 2000, 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=400'),
  (4, 'Pop Mie', 6000, 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=400'),
  (4, 'Mie Gelas', 2500, 'https://images.unsplash.com/photo-1552611052-33e04de081de?w=400'),
  -- USMAN 7
  (5, 'Tempura', 1000, 'https://images.unsplash.com/photo-1581184953963-d159747d1286?w=400'),
  (5, 'Nasi Goreng', 1000, 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400'),
  -- USMAN 8
  (6, 'Nasi Geprek', 7000, 'https://images.unsplash.com/photo-1606080206121-aee43df79768?w=400'),
  (6, 'Donat', 3000, 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=400'),
  (6, 'Risol', 3000, 'https://images.unsplash.com/photo-1625938146369-adc83368bda7?w=400'),
  (6, 'Es Sirup', 3000, 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=400');

-- Menghapus RLS (Row Level Security) agar bisa diakses langsung (karena kita menggunakan anon key tanpa user login supabase)
-- PENTING: Untuk aplikasi sungguhan, sebaiknya RLS diaktifkan. Namun untuk mempermudah saat ini, kita akan matikan sementara atau buat policy allow all.

ALTER TABLE kantin DISABLE ROW LEVEL SECURITY;
ALTER TABLE menu DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE reviews DISABLE ROW LEVEL SECURITY;
