-- Script SQL untuk membuat tabel di Supabase
-- Jalankan kode ini di fitur "SQL Editor" pada dashboard Supabase Anda.

-- 1. Membuat tabel 'kantin'
CREATE TABLE IF NOT EXISTS kantin (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama TEXT NOT NULL,
  icon TEXT NOT NULL
);

-- 2. Membuat tabel 'menu'
CREATE TABLE IF NOT EXISTS menu (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kantin_id BIGINT REFERENCES kantin(id) ON DELETE CASCADE,
  nama TEXT NOT NULL,
  harga INT NOT NULL,
  img TEXT NOT NULL
);

-- 3. Membuat tabel 'orders'
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  items TEXT NOT NULL,
  total_price INT NOT NULL,
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Membuat tabel 'reviews'
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  review_text TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Memasukkan data awal (dummy data) untuk tabel kantin
INSERT INTO kantin (nama, icon) VALUES 
  ('USMAN 1', '🍱'),
  ('USMAN 2', '🍲'),
  ('USMAN 3', '🍜'),
  ('USMAN 4', '🍹'),
  ('USMAN 7', '☕'),
  ('USMAN 8', '🍙');

-- Memasukkan data awal (dummy data) untuk tabel menu (berdasarkan kantin_id 1 yaitu USMAN 1)
INSERT INTO menu (kantin_id, nama, harga, img) VALUES 
  (1, 'Bakpao', 2500, 'Gambar/bakpao.jpg'),
  (1, 'Pentol', 5000, 'Gambar/pentol.jpg'),
  (1, 'Gorengan', 1000, 'Gambar/gorengan.jpg');

-- Menghapus RLS (Row Level Security) agar bisa diakses langsung (karena kita menggunakan anon key tanpa user login supabase)
-- PENTING: Untuk aplikasi sungguhan, sebaiknya RLS diaktifkan. Namun untuk mempermudah saat ini, kita akan matikan sementara atau buat policy allow all.

ALTER TABLE kantin DISABLE ROW LEVEL SECURITY;
ALTER TABLE menu DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE reviews DISABLE ROW LEVEL SECURITY;
